### ISSUE TITLE
Installing unpic in a next.js project causes module not found error

### ISSUE THREAD

**Issue by Fawwaz-2009** [ascorbic/unpic-img#118]
Hey Matt Thanks for all hard work and excited for the future of `unpic` 👍 .

**Describe the bug**
Installing and using `@unpic/react` in a next.js project cause `module not found` error.

**More details:**  I first tried to use `@unpic/react` in my personal project and I got the `Cannot find module`. Then I tried with a next nextjs project  and got `module not found` error. Thought it's not the same module..... I think.

**To Reproduce**
1. Install `@unpic/react`
2. use the same example form the next.js example documentation.
3. See sandbox for reference. https://codesandbox.io/p/sandbox/distracted-wood-j0jjcw?file=%2Fpages%2Findex.tsx

**Expected behavior**
To be working without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/32019791/225658105-f74593f4-e715-47a8-94bc-1f4093ad7e15.png)

![image](https://user-images.githubusercontent.com/32019791/225658194-f783a240-1a24-40b6-9950-593e0c8a6bc9.png)

**Comment by bjcgg** [comment]
Yeah I have the same issue just now.

**Comment by bjcgg** [comment]
I deleted `node_modules` and `yarn.lock` and did a clean install and it works flawlessly on next 13.2.4

**Comment by clementoriol** [comment]
Got the same error. I'm using pnpm and I've got the feeling that this could be related to pnpm module resolution mechanism.

I've setup a fresh repo  (create-next-app + unpic/img) to showcase the issue : https://github.com/clementoriol/unpic-img-pnpm-issue

```
pnp install
pnp dev
```

and you should see the error when loading `localhost:3000` :  
```
Error: Cannot find module '(...)/node_modules/.pnpm/@unpic+react@0.0.20_ld2jel3hspngo3u5lti2kgl2sq/node_modules/next/dist/shared/lib/image-config' imported from (...)/node_modules/.pnpm/@unpic+react@0.0.20_ld2jel3hspngo3u5lti2kgl2sq/node_modules/@unpic/react/dist/next.mjs
Did you mean to import next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/image-config.js?
```

**Comment by clementoriol** [comment]
Update. Encountered the same error on another project which uses npm, so I think we can rule out pnpm.

The project uses `next@13.3.0` (with typescript) + `@unpic/react@0.0.28`.

I'm having issues understanding the exact cause but this seems related to the following issue : 
https://github.com/vercel/next.js/issues/40632

I've tried the suggested fixes in the issue with no result.

The issue seems caused by the two imports in `node_modules/@unpic/react/next.mjs` :  
```
import { ImageConfigContext } from "next/dist/shared/lib/image-config-context";
import { imageConfigDefault } from "next/dist/shared/lib/image-config";
```

Adding the .js extension to those files (as a test) both fixes the issue.

**What do you think about specifying those extensions to `https://github.com/ascorbic/unpic-img/blob/main/packages/react/src/next.tsx` ?**

**Comment by Fawwaz-2009** [comment]
just did the same test as @clementoriol and it did indeed fixed the error.

**Comment by ascorbic** [comment]
Oh, interesting. Nice find. There shouldn't be a problem with adding extensions to all the deep imports.
